In [1]:
import urllib2
from scipy import stats
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data'
raw_csv = urllib2.urlopen(path)
col_names = range(23)
df = pd.read_csv(raw_csv, names = col_names)

In [2]:
map_dic = {}
num_columns = df.shape[1]
for i in range(num_columns):
    unique_array = df[i].unique()
    map_dic_sub = {}
    for j in range(len(unique_array)):
        map_dic_sub[unique_array[j]] = j
    df[i] = df[i].map(map_dic_sub)
df.head()

0   1   2   3   4   5   6   7   8   9  ...  13  14  15  16  17  18  19  20  \
0   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   0   
1   1   0   0   1   0   1   0   0   1   0 ...   0   0   0   0   0   0   0   1   
2   1   1   0   2   0   2   0   0   1   1 ...   0   0   0   0   0   0   0   1   
3   0   0   1   2   0   0   0   0   0   1 ...   0   0   0   0   0   0   0   0   
4   1   0   0   3   1   3   0   1   1   0 ...   0   0   0   0   0   0   1   1   

   21  22  
0   0   0  
1   1   1  
2   1   2  
3   0   0  
4   2   1  

[5 rows x 23 columns]

In [3]:
attributes = df.iloc[:, 1:23]
attributes.head()

1   2   3   4   5   6   7   8   9   10 ...  13  14  15  16  17  18  19  20  \
0   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   0   
1   0   0   1   0   1   0   0   1   0   0 ...   0   0   0   0   0   0   0   1   
2   1   0   2   0   2   0   0   1   1   0 ...   0   0   0   0   0   0   0   1   
3   0   1   2   0   0   0   0   0   1   0 ...   0   0   0   0   0   0   0   0   
4   0   0   3   1   3   0   1   1   0   1 ...   0   0   0   0   0   0   1   1   

   21  22  
0   0   0  
1   1   1  
2   1   2  
3   0   0  
4   2   1  

[5 rows x 22 columns]

In [4]:
mushroom_data = attributes.values
mushroom_data

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 1, 1],
       [1, 0, 2, ..., 1, 1, 2],
       ..., 
       [3, 0, 0, ..., 8, 5, 6],
       [4, 1, 0, ..., 4, 3, 6],
       [0, 0, 0, ..., 6, 5, 6]], dtype=int64)

In [5]:
target_series = df.iloc[:, 0]
target_series.head()

0    0
1    1
2    1
3    0
4    1
Name: 0, dtype: int64

In [6]:
mushroom_target = target_series.values
mushroom_target

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

In [7]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion='entropy')
clf = clf.fit(mushroom_data, mushroom_target)

In [8]:
with open("mushroom.dot", 'w') as f2:
    tree.export_graphviz(clf, out_file=f2)

In [9]:
mushroom_data[-1]

array([ 0,  0,  0,  1,  3,  1,  0,  1, 10,  0,  4,  0,  0,  6,  7,  0,  2,
        0,  0,  6,  5,  6], dtype=int64)

In [10]:
clf.predict(mushroom_data[-1].reshape(1,-1))

array([1], dtype=int64)

In [11]:
clf.predict(mushroom_data[-2].reshape(1,-1))


array([0], dtype=int64)

In [12]:
import findspark     
 
findspark.init()  
from pyspark import SparkContext, SparkFiles, SQLContext

if not 'sc' in locals():  
    sc = SparkContext()  

sqlCtx = SQLContext(sc)
sdf = sqlCtx.createDataFrame(df)
sdf.show()
#sdf.printSchema()
print "Raw data size is %s" % sdf.count()

IllegalArgumentException: u'java.net.URISyntaxException: Relative path in absolute URI: file:C:/Users/hojoong/datascience/spark-warehouse'